version: "2"

services:
  postgres:
    image: postgres:9.5
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5431:5432

  redis:
    image: redis:3.0-alpine
    command: redis-server --requirepass devpassword
    volumes:
      - redis:/var/lib/redis/data
    ports:
      - 6379:6379

  website:
    build: .
    command: >
      gunicorn -c "python:config.gunicorn" --reload "snakeeyes.app:create_app()"
    # command: >
    #   gunicorn -b 0.0.0.0:8000
    #     --access-logfile -
    #     --reload
    #     "snakeeyes.app:create_app()"
    environment:
      PYTHONUNBUFFERED: "true"
    volumes:
      - .:/snakeeyes
    # for local -> no nginx
    # ports:
    #   - "8000:8000"
    expose:
      - 8000
    env_file:
      - .env
    restart: "always"

  celery:
    build: .
    command: celery worker -B -l info -A snakeeyes.blueprints.contact.tasks
    env_file:
      - .env
    volumes:
      - .:/snakeeyes

  # celery_beat:
  #   build: .
  #   command: celery beat -l info -A snakeeyes.blueprints.contact.tasks
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/snakeeyes

  nginx:
    build: ./services/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - website
    volumes:
      - .:/etc/letsencrypt/live

volumes:
  postgres:
  redis:
