version: "2"

services:
  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "snakeeyes.app:create_app()"
    environment:
      PYTHONUNBUFFERED: "true"
    volumes:
      - ".:/snakeeyes"
    # ports:
    #   - "8000:8000"
    expose:
      - 8000
    env_file:
      - .env
  nginx:
    build: ./services/nginx
    ports:
      - 80:80
    depends_on:
      - website
